variables:
  azureSubscription: Free Trial
steps:

- task: AzureWebApp@1
  displayName: Azure Web App Deploy
  inputs:
    azureSubscription: $(azureSubscription)
    appName: hdbwebapp
    package: $(System.DefaultWorkingDirectory)/**/*.zip
apptyp: AzureWebApp

