variables:
  azureSubscription:2a124908-ff62-4ac7-b54a-f8d87033a1d0
  # To ignore SSL error uncomment the below variable
  # VSTS_ARM_REST_IGNORE_SSL_ERRORS: true

steps:

- task: AzureWebApp
  displayName: Azure Web App Deploy
  inputs:
    azureSubscription: $(azureSubscription)
    appName: hdbwebapp
    package: $(System.DefaultWorkingDirectory)/**/*.zip